name: Terraform CI

on:
  pull_request:
    paths:
      - 'tf/**.tf'
      - 'tf/tests/**.tftest.hcl'
      - '.github/workflows/*.yaml'
  push:
    branches: [ main ]
    paths:
      - 'tf/**.tf'
      - 'tf/tests/**.tftest.hcl'
      - '.github/workflows/*.yaml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # checkout
      security-events: write  # tfsec SARIF を Code Scanning に出す場合

    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:    ap-northeast-1

    # すべての terraform コマンドは tf ディレクトリで実行
    defaults:
      run:
        working-directory: tf

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
          terraform_wrapper: false

      # ---------- Validate / Test ----------
      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform test
        run: terraform test -no-color

      # ---------- TFLint ----------
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4   # installs & caches tflint
      - name: Run TFLint
        run: |
          tflint --init
          tflint --format compact

      # ---------- tfsec ----------
      - name: tfsec (IaC セキュリティスキャン)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: false     # true にすると警告のみで CI 通過

      # ---------- Plan (Dry‑Run) ----------
      - name: Terraform plan (save to file)
        run: terraform plan -input=false -no-color